[package]
name = "solana-alt-store"
author = "Andrew Fitzgerald <apfitzge@gmail.com>"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { version = "1.3.3" }
serde = { version = "1.0.189" }
solana-client = { version = "1.17.20" }
solana-sdk = { version = "1.17.20" }
